export const BundleAsset = {
    url1: "src/assets/images/Chat150.png",
  url2: "src/assets/images/busin21.png",
  url3: "src/assets/images/Chat17.png",
  "url4": "src/assets/images/Midj.png",
  "url5": "src/assets/images/Kids.png",
  "url6": "src/assets/images/8000cook.png",
  "url7": "src/assets/images/Planner.png",
  "url8": "src/assets/images/canva.png",
  "url9": "src/assets/images/400ebook.png",
  "url10": "src/assets/images/land.png",
  "url11": "src/assets/images/resume.png",
  "url12": "src/assets/images/office.png",
  "url13": "src/assets/images/1800cook.png",
  "url14": "src/assets/images/sound450.png",
  "url15": "src/assets/images/guide.png",
}